In [1]:
import numpy as np

In [4]:
arr1=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
arr2=[1,2,3,4,5,6,7,8,9,10,11,12]
arr3=[1,2,3,4,5,6]
arr4=[1,2]

In [5]:
arr1=np.array(arr1)
arr2=np.array(arr2)
arr3=np.array(arr3)
arr4=np.array(arr4)

In [6]:
arr1=arr1.reshape(5,4)
arr2=arr2.reshape(4,3)
arr3=arr3.reshape(3,2)
arr4=arr4.reshape(2,1)

In [16]:
#matrix addition
a=[[1,2,3],[3,45,7]]
b=[[2,3,4],[1,2,3]]
a=np.array(a)
b=np.array(b)
print(np.add(a,b))

[[ 3  5  7]
 [ 4 47 10]]


In [7]:
a=np.dot(arr1,arr2)
b=np.dot(a,arr3)
c=np.dot(b,arr4)

In [8]:
print(c)

[[ 2760]
 [ 6384]
 [10008]
 [13632]
 [17256]]


In [10]:

print(arr1.transpose())

[[ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]
 [ 4  8 12 16 20]]


In [89]:
#question 3

In [1]:
import numpy as np
  
# Taking a 3 * 3 matrix
A111 = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
  
# Calculating the inverse of the matrix
print(np.linalg.inv(A111))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [2]:
#Python implementation of Hebbian Learning on XOR logic gates.
def hebbian_learning(samples):
     print(f'{"INPUT":^8} {"TARGET":^16}{"WEIGHT CHANGES":^15}{"WEIGHTS":^25}')
     w1, w2, b = 0, 0, 0
     print(' ' * 45, f'({w1:2}, {w2:2}, {b:2})')
     for x1, x2, y in samples:
         w1 = w1 + x1 * y
         w2 = w2 + x2 * y
         b = b + y
         print(f'({x1:2}, {x2:2})          {y:2}     ({x1*y:2}, {x2*y:2}, {y:2})       ({w1:2}, {w2:2}, {b:2})')

XOR_samples = {
    'binary_input_binary_output': [
        [1, 1, 0], [1, 0, 1], [0, 1, 1], [0, 0, 0] ],
    'binary_input_bipolar_output': [
        [1, 1, -1], [1, 0, 1], [0, 1, 1], [0, 0, -1] ],
    'bipolar_input_bipolar_output': [
        [ 1, 1, -1], [ 1, -1, 1], [-1, 1, 1], [-1, -1, -1] ]
}

print('XOR with binary input and binary output')
hebbian_learning(XOR_samples['binary_input_binary_output'])
print('XOR with binary input and bipolar output')
hebbian_learning(XOR_samples['binary_input_bipolar_output'])
print('XOR with bipolar input and bipolar output')
hebbian_learning(XOR_samples['bipolar_input_bipolar_output'])

XOR with binary input and binary output
 INPUT        TARGET     WEIGHT CHANGES          WEIGHTS         
                                              ( 0,  0,  0)
( 1,  1)           0     ( 0,  0,  0)       ( 0,  0,  0)
( 1,  0)           1     ( 1,  0,  1)       ( 1,  0,  1)
( 0,  1)           1     ( 0,  1,  1)       ( 1,  1,  2)
( 0,  0)           0     ( 0,  0,  0)       ( 1,  1,  2)
XOR with binary input and bipolar output
 INPUT        TARGET     WEIGHT CHANGES          WEIGHTS         
                                              ( 0,  0,  0)
( 1,  1)          -1     (-1, -1, -1)       (-1, -1, -1)
( 1,  0)           1     ( 1,  0,  1)       ( 0, -1,  0)
( 0,  1)           1     ( 0,  1,  1)       ( 0,  0,  1)
( 0,  0)          -1     ( 0,  0, -1)       ( 0,  0,  0)
XOR with bipolar input and bipolar output
 INPUT        TARGET     WEIGHT CHANGES          WEIGHTS         
                                              ( 0,  0,  0)
( 1,  1)          -1     (-1, -1, -1)       (-

In [18]:
#Python implementation of Hebbian Learning on XOR logic gates.
def hebbian_or_learning(samples):
     print(f'{"INPUT":^8} {"TARGET":^16}{"WEIGHT CHANGES":^15}{"WEIGHTS":^25}')
     w1, w2, b = 0, 0, 0
     print(' ' * 45, f'({w1:2}, {w2:2}, {b:2})')
     for x1, x2, y in samples:
         w1 = w1 + x1 * y
         w2 = w2 + x2 * y
         b = b + y
         print(f'({x1:2}, {x2:2})          {y:2}     ({x1*y:2}, {x2*y:2}, {y:2})       ({w1:2}, {w2:2}, {b:2})')

OR_samples = {
    'binary_input_binary_output': [
        [1, 1, 1], [1, 0, 1], [0, 1, 1], [0, 0, 0] ],
    'binary_input_bipolar_output': [
        [1, 1, 1], [1, 0, 1], [0, 1, 1], [0, 0, -1] ],
    'bipolar_input_bipolar_output': [
        [ 1, 1, 1], [ 1, -1, 1], [-1, 1, 1], [-1, -1, -1] ]
}

print('OR with binary input and binary output')
hebbian_or_learning(OR_samples['binary_input_binary_output'])
print('OR with binary input and bipolar output')
hebbian_or_learning(OR_samples['binary_input_bipolar_output'])
print('OR with bipolar input and bipolar output')
hebbian_or_learning(OR_samples['bipolar_input_bipolar_output'])

OR with binary input and binary output
 INPUT        TARGET     WEIGHT CHANGES          WEIGHTS         
                                              ( 0,  0,  0)
( 1,  1)           1     ( 1,  1,  1)       ( 1,  1,  1)
( 1,  0)           1     ( 1,  0,  1)       ( 2,  1,  2)
( 0,  1)           1     ( 0,  1,  1)       ( 2,  2,  3)
( 0,  0)           0     ( 0,  0,  0)       ( 2,  2,  3)
OR with binary input and bipolar output
 INPUT        TARGET     WEIGHT CHANGES          WEIGHTS         
                                              ( 0,  0,  0)
( 1,  1)           1     ( 1,  1,  1)       ( 1,  1,  1)
( 1,  0)           1     ( 1,  0,  1)       ( 2,  1,  2)
( 0,  1)           1     ( 0,  1,  1)       ( 2,  2,  3)
( 0,  0)          -1     ( 0,  0, -1)       ( 2,  2,  2)
OR with bipolar input and bipolar output
 INPUT        TARGET     WEIGHT CHANGES          WEIGHTS         
                                              ( 0,  0,  0)
( 1,  1)           1     ( 1,  1,  1)       ( 1, 

In [20]:
#Python implementation of Hebbian Learning on XOR logic gates.
def hebbian_and_learning(samples):
     print(f'{"INPUT":^8} {"TARGET":^16}{"WEIGHT CHANGES":^15}{"WEIGHTS":^25}')
     w1, w2, b = 0, 0, 0
     print(' ' * 45, f'({w1:2}, {w2:2}, {b:2})')
     for x1, x2, y in samples:
         w1 = w1 + x1 * y
         w2 = w2 + x2 * y
         b = b + y
         print(f'({x1:2}, {x2:2})          {y:2}     ({x1*y:2}, {x2*y:2}, {y:2})       ({w1:2}, {w2:2}, {b:2})')

AND_samples = {
    'binary_input_binary_output': [
        [1, 1, 1], [1, 0, 0], [0, 1, 0], [0, 0, 0] ],
    'binary_input_bipolar_output': [
        [1, 1, 1], [1, 0, -1], [0, 1, -1], [0, 0, 0] ],
    'bipolar_input_bipolar_output': [
        [ 1, 1, 1], [ 1, -1, -1], [-1, 1, -1], [-1, -1, -1] ]
}

print('AND with binary input and binary output')
hebbian_and_learning(AND_samples['binary_input_binary_output'])
print('AND with binary input and bipolar output')
hebbian_and_learning(AND_samples['binary_input_bipolar_output'])
print('AND with bipolar input and bipolar output')
hebbian_and_learning(AND_samples['bipolar_input_bipolar_output'])

AND with binary input and binary output
 INPUT        TARGET     WEIGHT CHANGES          WEIGHTS         
                                              ( 0,  0,  0)
( 1,  1)           1     ( 1,  1,  1)       ( 1,  1,  1)
( 1,  0)           0     ( 0,  0,  0)       ( 1,  1,  1)
( 0,  1)           0     ( 0,  0,  0)       ( 1,  1,  1)
( 0,  0)           0     ( 0,  0,  0)       ( 1,  1,  1)
AND with binary input and bipolar output
 INPUT        TARGET     WEIGHT CHANGES          WEIGHTS         
                                              ( 0,  0,  0)
( 1,  1)           1     ( 1,  1,  1)       ( 1,  1,  1)
( 1,  0)          -1     (-1,  0, -1)       ( 0,  1,  0)
( 0,  1)          -1     ( 0, -1, -1)       ( 0,  0, -1)
( 0,  0)           0     ( 0,  0,  0)       ( 0,  0, -1)
AND with bipolar input and bipolar output
 INPUT        TARGET     WEIGHT CHANGES          WEIGHTS         
                                              ( 0,  0,  0)
( 1,  1)           1     ( 1,  1,  1)       ( 

In [22]:
#Question5
import math

In [23]:
def sig(x):
 return 1/(1 + math.exp(-x))

In [24]:
x1=0.2
x2=0.3
x3=0.9
output_1=x1*(-0.7)+x2*(-0.8)+x3*(0.2)
y1=output_1*(0.2)
y2=output_1*0.1
y3=output_1*0.2
z1=y1*0.4+y2*0.3
z2=y2*(-0.7)+y3*(0.8)
final=z1*(-0.2)+z2*(0.4)
final_y=sig(final)
print(final_y)

0.4993000004573329
