In [4]:
import numpy as np
import pandas as pd
import tensorflow as tf

Now after importing libraries


Data preprocessing 

In [5]:
data=pd.read_csv('/content/Churn_Modelling.csv')



In [6]:
X=data.iloc[:,3:-1].values
Y=data.iloc[:,-1].values


In [7]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [8]:
print(Y)

[1 0 1 ... 1 1 0]


Now as we can see in X there is categorical data and our neural network can only take numerical values
so we will encode it


In [9]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:,2]=le.fit_transform(X[:,2])
X[:,1]=le.fit_transform(X[:,1])

In [10]:
print("Male as",X[771,2])
print("Female as ",X[0,2])



Male as 1
Female as  0


Training and testing

In [11]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(X,Y,test_size=0.2,random_state=0)


Feature Scaling as neural network is based on gradient descent method it will take. a large time to find the minimum of cost function

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
xtrain = sc.fit_transform(xtrain)
xtest = sc.transform(xtest)

Starting with the ann initialise it using tensorflow keras

In [13]:
ann=tf.keras.models.Sequential()


adding layers using layers and dense method units is no of nodes we want in our hidden 1st layer

In [14]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

adding 2nd layer

In [15]:
#ann.add(tf.keras.layers.Dense(units=4, activation='relu'))

In [16]:
#ann.add(tf.keras.layers.Dense(units=3, activation='relu'))

In [17]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

adding output layer and using signoid function for the probabilty

In [18]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [19]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [20]:
ann.fit(xtrain, ytrain, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5585 - accuracy: 0.7837
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4924 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4634 - accuracy: 0.7965
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4411 - accuracy: 0.7993
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4237 - accuracy: 0.8123
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4103 - accuracy: 0.8207
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3981 - accuracy: 0.8325
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3858 - accuracy: 0.8403
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3752 - accuracy: 0.8480
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3675 - accura

### Predicting the Test set results

In [21]:
y_pred = ann.predict(xtest)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), ytest.reshape(len(ytest),1)),1))

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


Making confusion matrix for accuracy checking

In [22]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(ytest,y_pred)
print(cm)
print(accuracy_score(ytest,y_pred))

[[1519   76]
 [ 199  206]]
0.8625
